#ML Analysis

load in data
```{r}
TextFeatures <- read.csv2(file = "../Data/6 TextFeatures.csv", sep = ",")[,-1] #load in data minus csv-appended column
TextFeatures <- sapply(TextFeatures, as.numeric) #convert to numeric
```

split data into train and test
```{r}
set.seed(6164900) #seed for reproducability
splits <- sample(1:nrow(TextFeatures), size = floor(nrow(TextFeatures)*0.6))

train <- TextFeatures[splits, ]
test <- TextFeatures[-splits, ]

```

evaluation metrics
```{r}
source("Functions.R")
```

Multilinear Regression. Does not need CV in this case, no parameters to be tuned
```{r}
fit_lm <- lm(Rating ~ ., data = as.data.frame(train))
pred_lm <- predict(fit_lm, newdata = as.data.frame(test))
metrics_lm <- metrics(test[,1], pred_lm) #not bad actually

CIs <- confint(fit_lm, level = 0.95) #save CI
unimp <- rownames(CIs[CIs[,1] < 0 & CIs[,2] >0, ]) #unimportant predictors
imp_lm <- rownames(CIs)[!rownames(CIs) %in% unimp][-1] #important predictors
```

preprocess for other algorithms
```{r}
K <- 10 #number of CVs
train <- cbind(train, ind = sample(rep(1:K, length.out = nrow(train)))) #indicator variable
traindf <- as.data.frame(train)
testdf <- as.data.frame(test)

```

principle component analysis algorithm
```{r}
npc <- 1:4

metrics_lpcr <- list()
for(j in npc){
  metric_cv <- matrix(NA, K, 3)
  colnames(metric_cv) <- c("RMSE", "MAD", "R2")
  for(i in 1:K){
    traincv <- traindf[traindf$ind != i,]
    validation <- traindf[traindf$ind == i,]
   
   metric_cv[i,] <- LPCR(traincv, validation, npc = j)
  }
  metrics_lpcr[[j-(npc[1]-1)]] <- metric_cv
}

names(metrics_lpcr) <- sprintf("NPC%d", npc)

```

LPCR obtain best condition
```{r}
(eval_lpcr <- lapply(metrics_lpcr, function(x){ #obtain mean and variances of metrics over folds
  apply(x, 2, function(y){
    c(m = mean(y), variance = var(y))
  })
}))

RMSE_lpcr <- sapply(eval_lpcr, function(x){ #obtain RMSE values vector
  x[1,1]
})

RMSE_lpcr #not much difference between 3 and 4
names(which(RMSE_lpcr == min(RMSE_lpcr))) #using 4 PC's gives the lowest RMSE, however it is not much better than when 3 PC's are used, so 3 is preferred. 
```

LPCR obtain metrics. *do not forget to obtain important variables*
```{r}
LPCR(traindf, testdf, npc = 3)
```

